@ConcertBooking = https://localhost:5001

### Get all bookings
GET {{ConcertBooking}}/api/bookings
Accept: application/json

### Add a booking
POST {{ConcertBooking}}/api/bookings
Accept: application/json
Content-Type: application/json
{
  "CustomerId": 1,
  "PerforamnceId":7
}