// <auto-generated />
using System;
using ConcertBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcertBooking.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250219084902_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConcertBooking.Data.Entity.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PerformanceId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            PerformanceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            PerformanceId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            PerformanceId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            PerformanceId = 4
                        });
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Concert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A night of legendary rock performances.",
                            Title = "Rock Legends"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Smooth and soulful jazz performances.",
                            Title = "Jazz Night"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A showcase of the biggest pop hits.",
                            Title = "Pop Extravaganza"
                        });
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Password = "hashedpassword1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.smith@example.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            Password = "hashedpassword2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie.brown@example.com",
                            FirstName = "Charlie",
                            LastName = "Brown",
                            Password = "hashedpassword3"
                        });
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PerformanceDateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            ConcertId = 1,
                            Country = "USA",
                            PerformanceDateAndTime = new DateTime(2025, 6, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Venue = "Madison Square Garden"
                        },
                        new
                        {
                            Id = 2,
                            City = "Los Angeles",
                            ConcertId = 1,
                            Country = "USA",
                            PerformanceDateAndTime = new DateTime(2025, 6, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Venue = "Staples Center"
                        },
                        new
                        {
                            Id = 3,
                            City = "Chicago",
                            ConcertId = 2,
                            Country = "USA",
                            PerformanceDateAndTime = new DateTime(2025, 7, 10, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Venue = "Blue Note"
                        },
                        new
                        {
                            Id = 4,
                            City = "London",
                            ConcertId = 3,
                            Country = "UK",
                            PerformanceDateAndTime = new DateTime(2025, 8, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Venue = "O2 Arena"
                        });
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Booking", b =>
                {
                    b.HasOne("ConcertBooking.Data.Entity.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConcertBooking.Data.Entity.Performance", "Performance")
                        .WithMany("Bookings")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Performance", b =>
                {
                    b.HasOne("ConcertBooking.Data.Entity.Concert", "Concert")
                        .WithMany("Performances")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Concert", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ConcertBooking.Data.Entity.Performance", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
